version: '3'

services:
    database:
        platform: linux/x86_64
        image: mysql:8.0.27
        container_name: feelin_db
        environment:
            - MYSQL_DATABASE=feelinDB
            - MYSQL_ROOT_PASSWORD=feelin
            - MYSQL_USER=feelin
            - MYSQL_PASSWORD=feelin
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

    application:
        image: yeonsumia/waffle-music-sns:main
        restart: on-failure
        container_name: feelin_app
        ports:
            - "8080:8080"
        volumes:
            - ./resources:/resources
        depends_on:
            - database

    nginx:
        image: nginx
        container_name: feelin_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/certificate:/etc/letsencrypt/live/api-feelin.kro.kr
        depends_on:
            - application

volumes:
    mysql-data:
