version: '3'

services:
    database:
        platform: linux/x86_64
        image: mysql:8.0.27
        container_name: feelin_db
        environment:
            - MYSQL_DATABASE=feelinDB
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=feelin
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

        ports:
            - "3306:3306"
        volumes:
            - ./database/feelinDB:/var/lib/mysql

    application:
        restart: always
        image: yeonsumia/waffle-music-sns:develop
        container_name: feelin_app
        build: .
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/feelinDB?serverTimezone=UTC
            SRPING_DATASOURCE_USERNAME: feelin
            SPRING_DATASOURCE_PASSWORD: feelin
        ports:
            - "8080:8080"
        depends_on:
            - database
