spring:
  profiles:
    active: local

app:
  jwt:
    jwt-secret-key: document
    jwt-expiration-in-ms: 86400000
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://database:3306/feelinDB?serverTimezone=UTC&useSSL=false
    username: feelin
    password: feelin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
