spring:
  profiles:
    active: local
    group:
      local: mail, jwt
      deploy: deploy
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/feelin?serverTimezone=Asia/Seoul
    username: feelin
    password: feelinuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
