spring:
  profiles:
    active: local

app:
  jwt:
    jwt-secret-key: document
    jwt-expiration-in-ms: 86400000
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/feelin?serverTimezone=UTC
    username: feelin
    password: feelin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create