name: Deploy to AWS EC2 (prod)

on:
    push:
        branches: [ main ]

defaults:
    run:
        working-directory: .

jobs:
    deploy:
        name: deploy (prod)
        runs-on: ubuntu-latest
        environment: prod
        env:
            IMAGE_TAG: ${{ github.run_number }}
            BUILD_NUMBER: ${{ github.run_number }}
            ECR_REGISTRY: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com
            ECR_REPOSITORY: feelin-prod/feelin-social-server
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Create application-deploy.yml
              run: echo "${{ secrets.FEELIN_DEPLOY_PROD_YML }}" > ./application-prod.yml

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Docker Build, tag, and push image to ECR
              id: build-image
              run: |
                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --build-arg ENV=prod
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                  echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
